---
title: "Untitled"
format: html
editor: visual
---

```{r}
#| message: false
#| warning: false

library(tidyverse)
library(patchwork)
library(tidytext)

```

```{r}
my_plots_df <- starwars |> 
  select(name, height, mass, gender, sex, eye_color) |> 
  mutate(eye_color = fct_lump_min(eye_color, 10)) |> 
  nest(data = -gender) |>
  mutate(my_plot = map2(data, gender, function(x, y) {
    x |> 
      ggplot(aes(y = eye_color)) +
      geom_bar(width = .5) +
      labs(x = NULL, y = NULL, title = y) + 
      theme_void() 
  })) 


mp1 <- my_plots_df[1,3][[1]]
mp2 <- my_plots_df[2,3][[1]]

mp1[[1]] + mp2[[1]] 


```

```{r}
my_purrr_df <- starwars |> 
  drop_na(gender) |> 
  select(name, height, mass, gender, sex, eye_color) |> 
  mutate(eye_color = fct_lump_min(eye_color, 12)) |> # manipulate data for clarity
  summarise(total = n(), .by = c(eye_color, gender)) |> 
  mutate(total = if_else(gender == "feminine", total * 3, total)) |> # manipulate data for clarity
  nest(data = -gender) |> # head(1) |> unnest(data) 
  mutate(my_plot = map2(data, gender, function(my_df, my_gender) {
    my_df |> 
      ggplot(aes(y = eye_color, x = total, label = str_to_title(eye_color))) +
      geom_col() +
      geom_text(color = "ivory", size = 5, hjust = 1.2) +
      labs(x = NULL, y = NULL) + 
      theme_void() +
      labs(title = str_to_title(my_gender))
  }
  )) 

my_purrr_df

my_purrr_df$my_plot[1][[1]] + my_purrr_df$my_plot[2][[1]]
```

```{r}
star_fluid_df <- starwars |> 
  drop_na(gender) |> 
  count(eye_color, name = "total") |> 
  slice_max(total, n = 3) |> 
  mutate(gender = "fluid")
star_fluid_df
```

```{r}
starwars |> 
  drop_na(gender) |>
  select(name, height, mass, gender, sex, eye_color) |> 
  mutate(eye_color = fct_lump_min(eye_color, 12)) |> # manipulate data for clarity
  summarise(total = n(), .by = c(eye_color, gender)) |> 
  mutate(total = if_else(gender == "feminine", total * 3, total)) |> # manipulate data for clarity
  ggplot(aes(y = fct_rev(fct_reorder2(eye_color, total, gender)),
             x = total, 
             label = str_to_title(eye_color))) +
  geom_col(fill = "grey50") +
  geom_col(data = . %>% 
             slice_max(total, by = gender),
           fill = "darkorange") +
  geom_text(color = "ivory", size = 5, hjust = 1.5) +
  labs(x = NULL, y = NULL) +
  theme_void() +
  theme(strip.text = element_text(size = 20)) +
  facet_wrap(vars(str_to_title(gender)))
```

```{r}
starwars |> 
  drop_na(gender) |>
  select(name, height, mass, gender, sex, eye_color) |> 
  mutate(eye_color = fct_lump_min(eye_color, 12)) |> # manipulate data for clarity
  summarise(total = n(), .by = c(eye_color, gender)) |> 
  bind_rows(star_fluid_df) |> 
  mutate(total = if_else(gender == "feminine", total * 4, total)) |>  # manipulate data for clarity
  mutate(total = if_else(gender == "fluid", total * 2, total)) |> 
  ggplot(aes(y = fct_rev(fct_reorder2(eye_color, total, gender)),
             x = total, 
             label = str_to_title(eye_color))) +
  geom_col(fill = "grey50") +
  geom_col(data = . %>% 
             slice_max(total, by = gender),
           fill = "darkorange") +
  geom_text(color = "ivory", size = 5, hjust = 1.2) +
  labs(x = NULL, y = NULL) +
  theme_void() +
  theme(strip.text = element_text(size = 20)) +
  facet_wrap(vars(str_to_title(gender)), scales = "free")
```

```{r}
# manipulate data for clarity
star_fluid_df <- starwars |> 
  drop_na(gender) |> 
  count(eye_color, name = "total") |> 
  slice_max(total, n = 5) |> 
  mutate(gender = "fluid")

sw_special_df <- starwars |> 
  drop_na(gender) |>
  select(name, height, mass, gender, sex, eye_color) |> 
  mutate(eye_color = fct_lump_min(eye_color, 12)) |> 
  summarise(total = n(), .by = c(eye_color, gender)) |> 
  bind_rows(star_fluid_df) |> 
  mutate(total = if_else(gender == "feminine", total * 4, total)) |> 
  mutate(total = if_else(gender == "fluid", total * 2, total))  


# build faceted plot  
sw_special_df |> 
  ggplot(aes(y = reorder_within(eye_color, total, gender),
             x = total, 
             label = str_to_title(abbreviate(eye_color, 
                                             minlength = 5)))) +
  geom_col(fill = "grey90") +
  geom_col(data = sw_special_df |>  
             slice_max(total, by = gender),
           fill = "darkorange") +
  geom_text(color = "dodgerblue3", size = 5, 
            hjust = 1.1, nudge_y = 0.15) +
  geom_text(aes(label = total), hjust = 1.3, 
            nudge_y = -0.2,
            color = "dodgerblue3") +
  tidytext::scale_y_reordered() +
  theme_void() +
  theme(strip.text = element_text(size = 16),
        plot.title = element_text(size=22)) +
  facet_wrap(vars(str_to_title(gender)), scales = "free_y") +
  labs(title = "Eye Color by gender",
       subtitle = "Starwars characters\n", 
       caption = "Source: `dplyr::starwars`")
```
